### PR TITLE
Formatted link to GitHub announcement. Added link to template generator

### PR DESCRIPTION
**Pull request by TalAter**
Hi again Kent.

I spent last weekend creating a [template generator](https://www.talater.com/open-source-templates/) that can generate custom issue and pull request templates.

You just answer a few questions about your project (e.g. do you have automated testing? what environment does your project run on?), fall down a rabbit hole of Carroll and Lovecraftian madness, and finally download `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` files customized to your project. 

I thought it might be a good starting point for people finding your project and stumbling on that _UNMAINTAINED_ message.

### CODE REVIEW

**Comment by TalAter** [comment]
I would also love your help with the actual [templates](https://github.com/TalAter/open-source-templates/tree/master/site/templates) I created... I'm sure you'll have some ideas on how to improve them.

**Comment by kentcdodds** [comment]
Cool! I'll look at your templates later :-)

**Comment by kentcdodds** [comment]
Those templates look cool. I'm just really impressed by the site. Very cool!

**Comment by TalAter** [comment]
Cool!
Thank you :sparkles:

**Pull request merged**
